#!/usr/bin/env python3
"""
apply-qutebrowser-colors.py <colors.json> <output_dir>

Generates <output_dir>/colors-wal.py — hints get rounded corners and
extra padding, tabs get an accent-driven indicator, matching the
floating-pill bar look.
"""

import json
import sys


def main():
    if len(sys.argv) < 3:
        print("Usage: apply-qutebrowser-colors.py <colors.json> <output_dir>", file=sys.stderr)
        sys.exit(1)

    colors_json_path, output_dir = sys.argv[1], sys.argv[2]

    with open(colors_json_path, "r") as f:
        data = json.load(f)

    bg = data["special"]["background"]
    fg = data["special"]["foreground"]
    colors = data["colors"]
    accent = colors["color4"]
    accent2 = colors["color6"]
    error = colors["color1"]
    muted = colors["color8"]

    hints_radius = 8
    tabs_padding = "{'top': 6, 'bottom': 6, 'left': 10, 'right': 10}"
    selected_bg, selected_fg = accent, bg

    output = f"""# Auto-generated by the rice — don't hand-edit.

c.colors.webpage.bg = "{bg}"

c.colors.statusbar.normal.bg = "{bg}"
c.colors.statusbar.normal.fg = "{fg}"
c.colors.statusbar.insert.bg = "{accent}"
c.colors.statusbar.insert.fg = "{bg}"
c.colors.statusbar.command.bg = "{bg}"
c.colors.statusbar.command.fg = "{fg}"
c.colors.statusbar.url.fg = "{fg}"
c.colors.statusbar.url.success.http.fg = "{accent2}"
c.colors.statusbar.url.success.https.fg = "{accent2}"
c.colors.statusbar.url.error.fg = "{error}"
c.colors.statusbar.url.warn.fg = "{error}"
c.colors.statusbar.progress.bg = "{accent}"

c.colors.tabs.bar.bg = "{bg}"
c.colors.tabs.odd.bg = "{bg}"
c.colors.tabs.odd.fg = "{fg}"
c.colors.tabs.even.bg = "{bg}"
c.colors.tabs.even.fg = "{fg}"
c.colors.tabs.selected.odd.bg = "{selected_bg}"
c.colors.tabs.selected.odd.fg = "{selected_fg}"
c.colors.tabs.selected.even.bg = "{selected_bg}"
c.colors.tabs.selected.even.fg = "{selected_fg}"
c.colors.tabs.indicator.start = "{accent2}"
c.colors.tabs.indicator.stop = "{accent}"
c.colors.tabs.indicator.error = "{error}"
c.tabs.padding = {tabs_padding}

c.colors.completion.fg = "{fg}"
c.colors.completion.odd.bg = "{bg}"
c.colors.completion.even.bg = "{bg}"
c.colors.completion.category.bg = "{bg}"
c.colors.completion.category.fg = "{accent}"
c.colors.completion.category.border.top = "{muted}"
c.colors.completion.category.border.bottom = "{muted}"
c.colors.completion.item.selected.bg = "{selected_bg}"
c.colors.completion.item.selected.fg = "{selected_fg}"
c.colors.completion.item.selected.border.top = "{accent}"
c.colors.completion.item.selected.border.bottom = "{accent}"
c.colors.completion.item.selected.match.fg = "{selected_fg}"
c.colors.completion.match.fg = "{accent2}"
c.colors.completion.scrollbar.fg = "{accent}"
c.colors.completion.scrollbar.bg = "{bg}"

c.colors.hints.bg = "{accent}"
c.colors.hints.fg = "{bg}"
c.colors.hints.match.fg = "{accent2}"
c.hints.radius = {hints_radius}

c.colors.downloads.bar.bg = "{bg}"
c.colors.downloads.start.bg = "{accent}"
c.colors.downloads.start.fg = "{bg}"
c.colors.downloads.stop.bg = "{accent2}"
c.colors.downloads.stop.fg = "{bg}"
c.colors.downloads.error.bg = "{error}"
c.colors.downloads.error.fg = "{bg}"

c.colors.messages.info.bg = "{bg}"
c.colors.messages.info.fg = "{fg}"
c.colors.messages.info.border = "{muted}"
c.colors.messages.warning.bg = "{bg}"
c.colors.messages.warning.fg = "{error}"
c.colors.messages.warning.border = "{error}"
c.colors.messages.error.bg = "{error}"
c.colors.messages.error.fg = "{bg}"
c.colors.messages.error.border = "{error}"

c.colors.prompts.bg = "{bg}"
c.colors.prompts.fg = "{fg}"
c.colors.prompts.border = "1px solid {muted}"
c.colors.prompts.selected.bg = "{selected_bg}"
c.colors.prompts.selected.fg = "{selected_fg}"

c.colors.contextmenu.menu.bg = "{bg}"
c.colors.contextmenu.menu.fg = "{fg}"
c.colors.contextmenu.selected.bg = "{selected_bg}"
c.colors.contextmenu.selected.fg = "{selected_fg}"
"""

    out_path = f"{output_dir}/colors-wal.py"
    with open(out_path, "w") as f:
        f.write(output)

    print(f"qutebrowser: {out_path} written")


if __name__ == "__main__":
    main()
